export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_FAILURE= 'FETCH_COUNTRY_FAILURE'

export const FETCH_AVAILABILITY_REQUEST= 'FETCH_AVAILABILITY_REQUEST'
export const FETCH_AVAILABILITY_SUCCESS= 'FETCH_AVAILABILITY_SUCCESS'
export const FETCH_AVAILABILITY_FAILURE= 'FETCH_AVAILABILITY_FAILURE'

export const SELECTED_REGION = 'SELECTED_REGION'

export const SHOW_RESULT = 'SHOW_RESULT'
