export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE'

export const ADD_BOOKING_REQUEST = 'ADD_BOOKING_REQUEST'
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS'
export const ADD_BOOKING_FAILURE = 'ADD_BOOKING_FAILURE'

export const SHOW_RESULT = 'SHOW_RESULT'

