export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST'
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE'

export const FETCH_GLOBAL_REQUEST = 'FETCH_GLOBAL_REQUEST'
export const FETCH_GLOBAL_SUCCESS = 'FETCH_GLOBAL_SUCCESS'
export const FETCH_GLOBAL_FAILURE= 'FETCH_GLOBAL_FAILURE'

export const SET_ERROR= 'SET_ERROR'
